'use client'

import { useState, useEffect } from 'react'
import { getInvoices, createInvoice, updateInvoiceStatus } from '@/actions/invoices'
import { getDeals } from '@/actions/deals'

type Invoice = {
  id: string
  invoice_number: string
  amount: number
  status: 'draft' | 'sent' | 'paid' | 'overdue'
  due_date: string | null
  paid_at: string | null
  created_at: string
  deals: {
    title: string
    brands: { name: string } | null
  } | null
}

type Deal = {
  id: string
  title: string
  value: number
  brands?: { name: string }
}

const STATUS_STYLES = {
  draft: 'bg-gray-100 text-gray-600',
  sent: 'bg-blue-100 text-blue-700',
  paid: 'bg-green-100 text-green-700',
  overdue: 'bg-red-100 text-red-700',
}

async function generatePDF(invoice: Invoice): Promise<void> {
  const pdfLib = await import('pdf-lib')
  const PDFDocument = pdfLib.PDFDocument
  const rgb = pdfLib.rgb
  const StandardFonts = pdfLib.StandardFonts

  const doc = await PDFDocument.create()
  const page = doc.addPage([595, 842])
  const font = await doc.embedFont(StandardFonts.Helvetica)
  const bold = await doc.embedFont(StandardFonts.HelveticaBold)

  const brandName = invoice.deals?.brands?.name || 'Brand'
  const dealTitle = invoice.deals?.title || 'Deal'
  const lineItem = dealTitle + ' Content Creation'
  const amountStr = '$' + invoice.amount.toLocaleString()

  page.drawRectangle({ x: 0, y: 742, width: 595, height: 100, color: rgb(0.07, 0.07, 0.07) })
  page.drawText('INVOICE', { x: 40, y: 800, size: 28, font: bold, color: rgb(1, 1, 1) })
  page.drawText(invoice.invoice_number, { x: 40, y: 770, size: 12, font: font, color: rgb(0.7, 0.7, 0.7) })
  page.drawText(amountStr, { x: 400, y: 790, size: 24, font: bold, color: rgb(1, 1, 1) })
  page.drawText('Amount Due', { x: 400, y: 770, size: 10, font: font, color: rgb(0.7, 0.7, 0.7) })

  page.drawLine({ start: { x: 40, y: 710 }, end: { x: 555, y: 710 }, thickness: 1, color: rgb(0.9, 0.9, 0.9) })

  page.drawText('BILLED TO', { x: 40, y: 685, size: 9, font: bold, color: rgb(0.5, 0.5, 0.5) })
  page.drawText(brandName, { x: 40, y: 665, size: 14, font: bold, color: rgb(0.1, 0.1, 0.1) })
  page.drawText('FOR', { x: 300, y: 685, size: 9, font: bold, color: rgb(0.5, 0.5, 0.5) })
  page.drawText(dealTitle, { x: 300, y: 665, size: 14, font: bold, color: rgb(0.1, 0.1, 0.1) })

  page.drawRectangle({ x: 40, y: 580, width: 515, height: 30, color: rgb(0.96, 0.96, 0.96) })
  page.drawText('Description', { x: 55, y: 591, size: 10, font: bold, color: rgb(0.3, 0.3, 0.3) })
  page.drawText('Amount', { x: 470, y: 591, size: 10, font: bold, color: rgb(0.3, 0.3, 0.3) })

  page.drawText(lineItem, { x: 55, y: 558, size: 11, font: font, color: rgb(0.1, 0.1, 0.1) })
  page.drawText(amountStr, { x: 470, y: 558, size: 11, font: font, color: rgb(0.1, 0.1, 0.1) })

  page.drawLine({ start: { x: 40, y: 540 }, end: { x: 555, y: 540 }, thickness: 0.5, color: rgb(0.9, 0.9, 0.9) })

  page.drawText('Total', { x: 400, y: 518, size: 12, font: bold, color: rgb(0.1, 0.1, 0.1) })
  page.drawText(amountStr, { x: 470, y: 518, size: 14, font: bold, color: rgb(0.07, 0.07, 0.07) })

  if (invoice.due_date) {
    page.drawText('Due Date:', { x: 40, y: 480, size: 10, font: bold, color: rgb(0.5, 0.5, 0.5) })
    page.drawText(
      new Date(invoice.due_date).toLocaleDateString(),
      { x: 120, y: 480, size: 10, font: font, color: rgb(0.1, 0.1, 0.1) }
    )
  }

  page.drawText('Status: ' + invoice.status.toUpperCase(), { x: 40, y: 455, size: 10, font: bold, color: rgb(0.3, 0.3, 0.3) })

  page.drawRectangle({ x: 0, y: 0, width: 595, height: 60, color: rgb(0.07, 0.07, 0.07) })
  page.drawText('Thank you for working with me!', { x: 40, y: 28, size: 11, font: font, color: rgb(0.8, 0.8, 0.8) })
  page.drawText('Generated by Creator Brand Manager', { x: 340, y: 28, size: 9, font: font, color: rgb(0.5, 0.5, 0.5) })

  const pdfBytes = await doc.save()
console.log('PDF bytes generated:', pdfBytes.length)
const blob = new Blob([new Uint8Array(pdfBytes)], { type: 'application/pdf' })
const url = URL.createObjectURL(blob)
const a = document.createElement('a')
a.href = url
a.download = invoice.invoice_number + '.pdf'
a.style.display = 'none'
document.body.appendChild(a)
a.click()
document.body.removeChild(a)
setTimeout(() => URL.revokeObjectURL(url), 1000)
}

export default function InvoicesPage() {
  const [invoices, setInvoices] = useState<Invoice[]>([])
  const [deals, setDeals] = useState<Deal[]>([])
  const [loading, setLoading] = useState(true)
  const [showModal, setShowModal] = useState(false)
  const [saving, setSaving] = useState(false)
  const [dealId, setDealId] = useState('')
  const [amount, setAmount] = useState('')
  const [dueDate, setDueDate] = useState('')
  const [invoiceNumber, setInvoiceNumber] = useState('')

  useEffect(() => {
    async function load() {
      try {
        const [inv, dls] = await Promise.all([getInvoices(), getDeals()])
        setInvoices(inv || [])
        setDeals(dls || [])
        setInvoiceNumber('INV-' + String((inv || []).length + 1).padStart(3, '0'))
      } catch (e) {
        console.error(e)
      } finally {
        setLoading(false)
      }
    }
    load()
  }, [])

  const handleCreate = async () => {
    if (!dealId || !amount) return
    setSaving(true)
    try {
      const newInv = await createInvoice({
        deal_id: dealId,
        invoice_number: invoiceNumber,
        amount: parseFloat(amount),
        due_date: dueDate || null,
      })
      setInvoices((prev) => [newInv, ...prev])
      setShowModal(false)
      setDealId('')
      setAmount('')
      setDueDate('')
    } catch (e) {
      console.error(e)
    } finally {
      setSaving(false)
    }
  }

  const handleStatusChange = async (
    invoiceId: string,
    status: 'draft' | 'sent' | 'paid' | 'overdue'
  ) => {
    await updateInvoiceStatus(invoiceId, status)
    setInvoices((prev) =>
      prev.map((inv) => (inv.id === invoiceId ? { ...inv, status } : inv))
    )
  }

  const totalEarned = invoices
    .filter((i) => i.status === 'paid')
    .reduce((sum, i) => sum + i.amount, 0)

  const totalPending = invoices
    .filter((i) => i.status !== 'paid')
    .reduce((sum, i) => sum + i.amount, 0)

  if (loading) return <div className="p-8 text-gray-400">Loading invoices...</div>

  return (
    <div className="p-8">
      <div className="flex items-center justify-between mb-8">
        <div>
          <h2 className="text-2xl font-semibold text-gray-900">Invoices</h2>
          <p className="text-gray-500 mt-1">
            {'$' + totalEarned.toLocaleString() + ' earned'} &nbsp;&middot;&nbsp; {'$' + totalPending.toLocaleString() + ' pending'}
          </p>
        </div>
        <button
          onClick={() => setShowModal(true)}
          className="bg-gray-900 text-white px-4 py-2 rounded-lg text-sm font-medium hover:bg-gray-700 transition-colors"
        >
          + New Invoice
        </button>
      </div>

      <div className="grid grid-cols-4 gap-4 mb-8">
        {[
          { label: 'Total Invoices', value: invoices.length },
          { label: 'Paid', value: invoices.filter((i) => i.status === 'paid').length },
          { label: 'Pending', value: invoices.filter((i) => i.status === 'sent').length },
          { label: 'Overdue', value: invoices.filter((i) => i.status === 'overdue').length },
        ].map((stat) => (
          <div key={stat.label} className="bg-white rounded-xl border border-gray-200 p-4">
            <p className="text-xs text-gray-500">{stat.label}</p>
            <p className="text-2xl font-semibold text-gray-900 mt-1">{stat.value}</p>
          </div>
        ))}
      </div>

      {invoices.length === 0 && (
        <div className="flex flex-col items-center justify-center h-64 text-center">
          <p className="text-gray-600 font-medium">No invoices yet</p>
          <p className="text-gray-400 text-sm mt-1">Create your first invoice from a deal</p>
          <button
            onClick={() => setShowModal(true)}
            className="mt-4 bg-gray-900 text-white px-4 py-2 rounded-lg text-sm font-medium hover:bg-gray-700"
          >
            + New Invoice
          </button>
        </div>
      )}

      <div className="space-y-3">
        {invoices.map((invoice) => (
          <div
            key={invoice.id}
            className="bg-white rounded-xl border border-gray-200 p-5 flex items-center justify-between"
          >
            <div>
              <p className="text-sm font-semibold text-gray-900">{invoice.invoice_number}</p>
              <p className="text-xs text-gray-500 mt-0.5">
                {invoice.deals?.brands?.name || 'Unknown'} &mdash; {invoice.deals?.title || 'Unknown deal'}
              </p>
            </div>

            <div className="flex items-center gap-6">
              <p className="text-sm font-semibold text-gray-900">
                {'$' + invoice.amount.toLocaleString()}
              </p>

              {invoice.due_date && (
                <p className="text-xs text-gray-400">
                  Due {new Date(invoice.due_date).toLocaleDateString()}
                </p>
              )}

              <span className={'text-xs px-2 py-1 rounded-full font-medium ' + STATUS_STYLES[invoice.status]}>
                {invoice.status.charAt(0).toUpperCase() + invoice.status.slice(1)}
              </span>

              <select
                value={invoice.status}
                onChange={(e) => handleStatusChange(invoice.id, e.target.value as 'draft' | 'sent' | 'paid' | 'overdue')}
                className="text-xs border border-gray-200 rounded-lg px-2 py-1 focus:outline-none"
              >
                <option value="draft">Draft</option>
                <option value="sent">Sent</option>
                <option value="paid">Paid</option>
                <option value="overdue">Overdue</option>
              </select>

              <button
                onClick={() => generatePDF(invoice)}
                className="text-xs bg-gray-900 text-white px-3 py-1.5 rounded-lg hover:bg-gray-700 transition-colors"
              >
                Download PDF
              </button>
            </div>
          </div>
        ))}
      </div>

      {showModal && (
        <div className="fixed inset-0 bg-black/50 flex items-center justify-center z-50">
          <div className="bg-white rounded-2xl p-6 w-full max-w-md shadow-xl">
            <div className="flex items-center justify-between mb-6">
              <h3 className="text-lg font-semibold text-gray-900">New Invoice</h3>
              <button onClick={() => setShowModal(false)} className="text-gray-400 hover:text-gray-600">
                x
              </button>
            </div>

            <div className="space-y-4">
              <div>
                <label className="text-sm font-medium text-gray-700 block mb-1">Invoice number</label>
                <input
                  type="text"
                  value={invoiceNumber}
                  onChange={(e) => setInvoiceNumber(e.target.value)}
                  className="w-full border border-gray-200 rounded-lg px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-gray-900"
                />
              </div>

              <div>
                <label className="text-sm font-medium text-gray-700 block mb-1">Deal *</label>
                <select
                  value={dealId}
                  onChange={(e) => {
                    setDealId(e.target.value)
                    const deal = deals.find((d) => d.id === e.target.value)
                    if (deal) setAmount(String(deal.value || ''))
                  }}
                  className="w-full border border-gray-200 rounded-lg px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-gray-900"
                >
                  <option value="">Select a deal...</option>
                  {deals.map((d) => (
                    <option key={d.id} value={d.id}>
                      {d.title} - ${d.value}
                    </option>
                  ))}
                </select>
              </div>

              <div>
                <label className="text-sm font-medium text-gray-700 block mb-1">Amount (USD) *</label>
                <input
                  type="number"
                  placeholder="e.g. 1500"
                  value={amount}
                  onChange={(e) => setAmount(e.target.value)}
                  className="w-full border border-gray-200 rounded-lg px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-gray-900"
                />
              </div>

              <div>
                <label className="text-sm font-medium text-gray-700 block mb-1">Due date</label>
                <input
                  type="date"
                  value={dueDate}
                  onChange={(e) => setDueDate(e.target.value)}
                  className="w-full border border-gray-200 rounded-lg px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-gray-900"
                />
              </div>
            </div>

            <div className="flex gap-3 mt-6">
              <button
                onClick={() => setShowModal(false)}
                className="flex-1 border border-gray-200 text-gray-700 px-4 py-2 rounded-lg text-sm font-medium hover:bg-gray-50"
              >
                Cancel
              </button>
              <button
                onClick={handleCreate}
                disabled={saving || !dealId || !amount}
                className="flex-1 bg-gray-900 text-white px-4 py-2 rounded-lg text-sm font-medium hover:bg-gray-700 disabled:opacity-50"
              >
                {saving ? 'Creating...' : 'Create Invoice'}
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  )
}